name: Flake8

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  flake8:
    name: Run Flake8
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flake8
      run: |
        flake8 **/*.py